//! gRPC API types for KeelOS, generated from `proto/node.proto`.
//!
//! This crate is a thin wrapper around the code `tonic-prost-build` emits at
//! build time. It defines no hand-written types of its own; see
//! `proto/node.proto` for the authoritative interface contract.

pub mod node {
    // The contents of this module are generated by `tonic-prost-build` from
    // proto/node.proto on every build. Doc comments cannot be attached to the
    // generated items by hand, so `missing_docs` is suppressed here rather than
    // workspace-wide -- that keeps the lint meaningful for hand-written code.
    #![allow(missing_docs)]

    tonic::include_proto!("keel.v1");
}
